import type { MetadataRoute } from "next";

import { siteConfig } from "@/lib/config";

// Generated by Next at /manifest.webmanifest and linked into <head>
// automatically — no hand-written JSON, no <link> tag to maintain.
//
// SCOPE (owner decision, 2026-08-29): home-screen icon and standalone
// chrome ONLY. No customer accounts, no wallet, no stored payment, no
// offline mode. That constraint is what makes this safe: iOS gives an
// installed PWA its own storage jar, separate from Safari, which
// normally means people are silently signed out of the installed copy.
// With nothing stored client-side there is nothing to lose.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.name,
    // iOS truncates the home-screen label at roughly 12 characters, so
    // "The Courtroom" would render as "The Courtr...". This is what
    // actually appears under the icon.
    short_name: "Courtroom",
    description: siteConfig.description,
    start_url: "/",
    // Everything below "/" is in scope. It has to be: the installable
    // pages live at the root, so a narrower scope would push /book and
    // /open-play out of the app and into Safari.
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    // Matches --navy-900 in globals.css. Painted behind the app during
    // launch and behind the status bar, so a mismatch shows as a flash
    // of the wrong colour on open.
    background_color: "#0e1424",
    theme_color: "#0e1424",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Android crops icons to a circle or squircle. Without a maskable
      // variant it crops the "any" icon instead and clips the badge's
      // edges; with one, it uses art already drawn inside the safe zone.
      {
        src: "/icons/icon-512-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
