// The URL-safe form of a tournament's name — "Sayans and Friends
// Pickleball Tournament" -> "sayans-and-friends-pickleball-tournament",
// so the public page is /tournaments/sayans-and-friends-pickleball-tournament
// instead of /tournaments/clx8f2a9k0001.
//
// MUST stay in agreement with migration 74's own SQL, which slugifies
// existing rows with the same rules (lowercase, runs of non-alphanumerics
// collapse to one dash, ends trimmed). A row created before that migration
// and one created after should be indistinguishable.
//
// Accents are folded first (NFKD + strip combining marks) so "Ñito" becomes
// "nito" rather than losing the letter entirely — the SQL side sees already-
// normalized text for anything it backfills, and PostgreSQL's own lower()
// handles the ASCII range this reduces to.
const MAX_SLUG_LENGTH = 80;

export function slugifyTournamentName(name: string): string {
  const slug = name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_SLUG_LENGTH)
    // The slice can land mid-dash — trim again so a truncated slug never
    // ends in a stray separator.
    .replace(/-+$/g, "");

  // A name of pure punctuation ("!!!") reduces to nothing. The caller
  // (tournamentService.createTournament) disambiguates duplicates, so a
  // shared fallback here is safe — it just becomes tournament-2, -3, ...
  return slug || "tournament";
}

// Distinguishes a slug from the cuid the public route also still accepts,
// so a link shared before this feature existed keeps resolving. cuids are
// generated by Prisma's @default(cuid()): "c" + 24 lowercase alphanumerics,
// no dashes. A real slug of that exact shape is possible in theory but would
// have to be a single 25-character dashless word starting with "c" — at
// which point resolving by id first and falling back to slug still finds it.
export function looksLikeCuid(value: string): boolean {
  return /^c[a-z0-9]{24}$/.test(value);
}
